import {
  User,
  Business,
  ComplianceItem,
  Template,
  ActivityLog,
} from "./types";

// Reference date: 2026-05-30
const T = "2026-05-30";

const d = (offset: number): string => {
  const base = new Date("2026-05-30");
  base.setDate(base.getDate() + offset);
  return base.toISOString().split("T")[0];
};

// ─── USERS ─────────────────────────────────────────────────────────────────

export const MOCK_USERS: User[] = [
  {
    id: "user_1",
    name: "Alice Morgan",
    email: "alice@designbyform.com",
    role: "owner",
    created_at: "2025-01-15T10:00:00Z",
  },
  {
    id: "user_concierge",
    name: "Jordan Rivera",
    email: "jordan@backstops.com",
    role: "concierge",
    created_at: "2025-02-01T10:00:00Z",
  },
];

// ─── BUSINESSES ────────────────────────────────────────────────────────────

export const MOCK_BUSINESSES: Business[] = [
  {
    id: "biz_lightsleeper",
    user_id: "user_1",
    name: "Light Sleeper Wine Bar",
    business_type: "Wine Bar",
    address: "1412 14th St NW",
    city: "Washington",
    county: "District of Columbia",
    state: "DC",
    zip: "20005",
    federal_requirements: false,
    responsible_contact_name: "Sarah Chen",
    responsible_contact_email: "sarah@lightsleeper.com",
    notes:
      "Full bar, wine-focused. ABRA license holder. 80 seats, live music some weekends.",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: d(-10),
  },
  {
    id: "biz_kilyimport",
    user_id: "user_1",
    name: "Kily Import",
    business_type: "Wine Importer",
    address: "3350 M St NW, Suite 400",
    city: "Washington",
    county: "District of Columbia",
    state: "DC",
    zip: "20007",
    federal_requirements: true,
    responsible_contact_name: "Marcus Wright",
    responsible_contact_email: "marcus@kilyimport.com",
    notes:
      "Federal Basic Permit holder. Primarily imports from France and Spain. Warehouse in Maryland.",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-5),
  },
  {
    id: "biz_foodtruck",
    user_id: "user_1",
    name: "Capitol Hill Food Truck",
    business_type: "Food Truck",
    address: "701 Pennsylvania Ave SE",
    city: "Washington",
    county: "District of Columbia",
    state: "DC",
    zip: "20003",
    federal_requirements: false,
    responsible_contact_name: "Priya Patel",
    responsible_contact_email: "priya@capitolhillft.com",
    notes:
      "Operates Monday–Friday on Capitol Hill. Uses commissary at Union Kitchen.",
    created_at: "2025-04-01T10:00:00Z",
    updated_at: d(-3),
  },
];

// ─── COMPLIANCE ITEMS ──────────────────────────────────────────────────────

export const MOCK_COMPLIANCE_ITEMS: ComplianceItem[] = [
  // ── Light Sleeper Wine Bar ──────────────────────────────────────────────
  {
    id: "ci_ls_01",
    business_id: "biz_lightsleeper",
    title: "City Business License Renewal",
    category: "Business License",
    status: "Overdue",
    priority: "Critical",
    due_date: d(-15),
    renewal_date: d(-15 + 365),
    frequency: "Annual",
    assigned_owner: "Sarah Chen",
    agency: "DC DLCP",
    jurisdiction: "District of Columbia",
    requires_document: true,
    document_url: "",
    document_status: "missing",
    reminder_days_before: 60,
    last_completed_date: "2025-05-15",
    notes:
      "Basic Business License renewal. Must be completed at DLCP or online. Fine for late filing is $150.",
    completion_notes: "",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: d(-1),
  },
  {
    id: "ci_ls_02",
    business_id: "biz_lightsleeper",
    title: "ABRA Retailer Liquor License Renewal",
    category: "Alcohol License",
    status: "In Progress",
    priority: "Critical",
    due_date: d(11),
    renewal_date: d(11 + 365),
    frequency: "Annual",
    assigned_owner: "Sarah Chen",
    agency: "DC ABRA",
    jurisdiction: "District of Columbia",
    requires_document: true,
    document_url: "https://abra.dc.gov/licenses",
    document_status: "uploaded",
    reminder_days_before: 90,
    last_completed_date: "2025-06-10",
    notes:
      "Retailer CR/DL license. Application in process. Must include Certificate of Occupancy and floor plan.",
    completion_notes: "",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: d(-2),
  },
  {
    id: "ci_ls_03",
    business_id: "biz_lightsleeper",
    title: "Health Department Food Service Permit",
    category: "Health Permit",
    status: "Not Started",
    priority: "High",
    due_date: d(32),
    renewal_date: d(32 + 365),
    frequency: "Annual",
    assigned_owner: "Sarah Chen",
    agency: "DC DOH",
    jurisdiction: "District of Columbia",
    requires_document: true,
    document_url: "",
    document_status: "missing",
    reminder_days_before: 45,
    last_completed_date: "2025-07-01",
    notes: "Annual food establishment permit. Requires recent inspection pass.",
    completion_notes: "",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: d(-5),
  },
  {
    id: "ci_ls_04",
    business_id: "biz_lightsleeper",
    title: "Liquor Liability Insurance Certificate",
    category: "Insurance",
    status: "In Progress",
    priority: "Critical",
    due_date: d(16),
    renewal_date: d(16 + 365),
    frequency: "Annual",
    assigned_owner: "Sarah Chen",
    agency: "Insurance Provider",
    jurisdiction: "DC",
    requires_document: true,
    document_url: "",
    document_status: "missing",
    reminder_days_before: 30,
    last_completed_date: "2025-06-15",
    notes:
      "ABRA requires certificate of insurance naming DC as additional insured. Minimum $1M coverage.",
    completion_notes: "",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: d(-1),
  },
  {
    id: "ci_ls_05",
    business_id: "biz_lightsleeper",
    title: "Food Handler Cards — Staff Renewal",
    category: "Food Handler / Safety",
    status: "Due Soon",
    priority: "Medium",
    due_date: d(6),
    renewal_date: d(6 + 365),
    frequency: "Annual",
    assigned_owner: "Sarah Chen",
    agency: "DC DOH",
    jurisdiction: "DC",
    requires_document: false,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 30,
    last_completed_date: "2025-06-05",
    notes:
      "All food handlers must hold valid DC Food Handler certification. 4 staff due this cycle.",
    completion_notes: "",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: d(-3),
  },
  {
    id: "ci_ls_06",
    business_id: "biz_lightsleeper",
    title: "Annual Fire Inspection",
    category: "Fire / Safety",
    status: "Not Started",
    priority: "High",
    due_date: d(76),
    renewal_date: d(76 + 365),
    frequency: "Annual",
    assigned_owner: "Sarah Chen",
    agency: "DC Fire and EMS",
    jurisdiction: "DC",
    requires_document: true,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 30,
    last_completed_date: "2025-08-15",
    notes: "Schedule through DC Fire Marshal. Certificate must be posted.",
    completion_notes: "",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: d(-10),
  },
  {
    id: "ci_ls_07",
    business_id: "biz_lightsleeper",
    title: "Music Licensing — ASCAP/BMI Renewal",
    category: "Other",
    status: "Not Started",
    priority: "Low",
    due_date: d(93),
    renewal_date: d(93 + 365),
    frequency: "Annual",
    assigned_owner: "Sarah Chen",
    agency: "ASCAP / BMI",
    jurisdiction: "Federal",
    requires_document: false,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 30,
    last_completed_date: "2025-09-01",
    notes:
      "Blanket license for live and recorded music. Check both ASCAP and BMI coverage.",
    completion_notes: "",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: d(-20),
  },
  {
    id: "ci_ls_08",
    business_id: "biz_lightsleeper",
    title: "DC Annual Biennial Report (Corporate Filing)",
    category: "Corporate Filing",
    status: "Waiting on Agency",
    priority: "Medium",
    due_date: d(62),
    renewal_date: d(62 + 730),
    frequency: "Biennial",
    assigned_owner: "Sarah Chen",
    agency: "DC DCRA",
    jurisdiction: "DC",
    requires_document: true,
    document_url: "",
    document_status: "uploaded",
    reminder_days_before: 45,
    last_completed_date: "2024-07-31",
    notes:
      "Filed. Awaiting confirmation from DCRA. Expect 2–3 week processing time.",
    completion_notes: "",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: d(-2),
  },
  {
    id: "ci_ls_09",
    business_id: "biz_lightsleeper",
    title: "Required Labor Law Postings — Annual Update",
    category: "Required Posting",
    status: "Completed",
    priority: "Low",
    due_date: d(-60),
    renewal_date: d(-60 + 365),
    frequency: "Annual",
    assigned_owner: "Sarah Chen",
    agency: "DC DOES / DOL",
    jurisdiction: "DC / Federal",
    requires_document: false,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 14,
    last_completed_date: "2026-03-15",
    notes:
      "All required federal and DC labor law posters updated and posted in break room.",
    completion_notes: "Updated all 7 required posters. Ordered new set from DOL.",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "ci_ls_10",
    business_id: "biz_lightsleeper",
    title: "Q2 Payroll Tax Filing (941)",
    category: "Tax / Excise",
    status: "Not Started",
    priority: "High",
    due_date: d(31),
    renewal_date: null,
    frequency: "Quarterly",
    assigned_owner: "Sarah Chen",
    agency: "IRS / DC OTR",
    jurisdiction: "Federal / DC",
    requires_document: false,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 14,
    last_completed_date: "2026-04-30",
    notes:
      "IRS Form 941 due July 31. DC FR-900Q due concurrently. Coordinate with bookkeeper.",
    completion_notes: "",
    created_at: "2025-03-01T10:00:00Z",
    updated_at: d(-7),
  },

  // ── Kily Import ────────────────────────────────────────────────────────
  {
    id: "ci_ki_01",
    business_id: "biz_kilyimport",
    title: "TTB Basic Importer Permit — Annual Review",
    category: "TTB / Alcohol Federal",
    status: "Overdue",
    priority: "Critical",
    due_date: d(-29),
    renewal_date: d(-29 + 365),
    frequency: "Annual",
    assigned_owner: "Marcus Wright",
    agency: "TTB",
    jurisdiction: "Federal",
    requires_document: true,
    document_url: "",
    document_status: "missing",
    reminder_days_before: 60,
    last_completed_date: "2025-05-01",
    notes:
      "Basic Importer Permit review and renewal. Must file TTB Form 5100.24. Significant penalties for lapse.",
    completion_notes: "",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-5),
  },
  {
    id: "ci_ki_02",
    business_id: "biz_kilyimport",
    title: "FDA Food Facility Registration Renewal",
    category: "FDA / Federal",
    status: "Not Started",
    priority: "High",
    due_date: d(9),
    renewal_date: d(9 + 730),
    frequency: "Biennial",
    assigned_owner: "Marcus Wright",
    agency: "FDA",
    jurisdiction: "Federal",
    requires_document: false,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 30,
    last_completed_date: "2024-06-08",
    notes:
      "FDA registration for wine importer/warehouse. Renewal required every 2 years in even years.",
    completion_notes: "",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-10),
  },
  {
    id: "ci_ki_03",
    business_id: "biz_kilyimport",
    title: "DC Importer/Wholesaler License Renewal",
    category: "Alcohol License",
    status: "In Progress",
    priority: "High",
    due_date: d(46),
    renewal_date: d(46 + 365),
    frequency: "Annual",
    assigned_owner: "Marcus Wright",
    agency: "DC ABRA",
    jurisdiction: "DC",
    requires_document: true,
    document_url: "https://abra.dc.gov/import",
    document_status: "uploaded",
    reminder_days_before: 60,
    last_completed_date: "2025-07-15",
    notes:
      "ABRA Importer/Wholesaler license. Application submitted. Awaiting final approval.",
    completion_notes: "",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-3),
  },
  {
    id: "ci_ki_04",
    business_id: "biz_kilyimport",
    title: "Federal Excise Tax Return (Q2)",
    category: "Tax / Excise",
    status: "Overdue",
    priority: "Critical",
    due_date: d(-10),
    renewal_date: null,
    frequency: "Quarterly",
    assigned_owner: "Marcus Wright",
    agency: "TTB",
    jurisdiction: "Federal",
    requires_document: false,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 14,
    last_completed_date: "2026-02-14",
    notes:
      "TTB Federal Excise Tax return for wine. Due 14th of month following quarter end.",
    completion_notes: "",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-1),
  },
  {
    id: "ci_ki_05",
    business_id: "biz_kilyimport",
    title: "TTB COLA Certificate Tracker",
    category: "TTB / Alcohol Federal",
    status: "Not Started",
    priority: "Medium",
    due_date: d(63),
    renewal_date: null,
    frequency: "Custom",
    assigned_owner: "Marcus Wright",
    agency: "TTB",
    jurisdiction: "Federal",
    requires_document: true,
    document_url: "",
    document_status: "missing",
    reminder_days_before: 30,
    last_completed_date: null,
    notes:
      "Review all active COLA certificates for upcoming product launches. Verify label compliance.",
    completion_notes: "",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-20),
  },
  {
    id: "ci_ki_06",
    business_id: "biz_kilyimport",
    title: "General Liability Insurance — Annual Renewal",
    category: "Insurance",
    status: "In Progress",
    priority: "Critical",
    due_date: d(31),
    renewal_date: d(31 + 365),
    frequency: "Annual",
    assigned_owner: "Marcus Wright",
    agency: "Insurance Broker",
    jurisdiction: "DC / MD",
    requires_document: true,
    document_url: "",
    document_status: "missing",
    reminder_days_before: 30,
    last_completed_date: "2025-06-30",
    notes:
      "Annual GL renewal. Must include product liability rider. $2M minimum. Renewal quote pending.",
    completion_notes: "",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-2),
  },
  {
    id: "ci_ki_07",
    business_id: "biz_kilyimport",
    title: "Import Document Archive — Annual Review",
    category: "Vendor Documents",
    status: "Waiting on Client",
    priority: "Medium",
    due_date: d(122),
    renewal_date: null,
    frequency: "Annual",
    assigned_owner: "Marcus Wright",
    agency: "Internal",
    jurisdiction: "Federal",
    requires_document: true,
    document_url: "",
    document_status: "missing",
    reminder_days_before: 30,
    last_completed_date: "2025-09-15",
    notes:
      "Annual audit of import documents, shipper docs, customs clearance records. Client must provide Q1–Q2 shipment manifests.",
    completion_notes: "",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-8),
  },
  {
    id: "ci_ki_08",
    business_id: "biz_kilyimport",
    title: "Annual Report (Biennial — DC DCRA)",
    category: "Corporate Filing",
    status: "Not Started",
    priority: "Medium",
    due_date: d(107),
    renewal_date: d(107 + 365),
    frequency: "Biennial",
    assigned_owner: "Marcus Wright",
    agency: "DC DCRA",
    jurisdiction: "DC",
    requires_document: false,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 45,
    last_completed_date: "2025-09-15",
    notes: "Standard DC biennial report for LLC. Online filing at DCRA.",
    completion_notes: "",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-30),
  },
  {
    id: "ci_ki_09",
    business_id: "biz_kilyimport",
    title: "Maryland Warehouse Liability Insurance",
    category: "Insurance",
    status: "Due Soon",
    priority: "High",
    due_date: d(13),
    renewal_date: d(13 + 365),
    frequency: "Annual",
    assigned_owner: "Marcus Wright",
    agency: "Insurance Broker",
    jurisdiction: "Maryland",
    requires_document: true,
    document_url: "",
    document_status: "expired",
    reminder_days_before: 30,
    last_completed_date: "2025-06-12",
    notes:
      "Warehouse in MD requires separate liability policy. Prior certificate expired. Renewal in process.",
    completion_notes: "",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-4),
  },
  {
    id: "ci_ki_10",
    business_id: "biz_kilyimport",
    title: "Product Label Documentation — Current Portfolio",
    category: "Other",
    status: "Completed",
    priority: "Low",
    due_date: d(-60),
    renewal_date: null,
    frequency: "Custom",
    assigned_owner: "Marcus Wright",
    agency: "Internal",
    jurisdiction: "Federal",
    requires_document: true,
    document_url: "https://docs.kilyimport.com/labels",
    document_status: "uploaded",
    reminder_days_before: 14,
    last_completed_date: "2026-04-01",
    notes: "All current product labels logged and stored with COLA references.",
    completion_notes: "47 SKUs documented. Updated with 3 new additions from Spring import.",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: "2026-04-01T10:00:00Z",
  },
  {
    id: "ci_ki_11",
    business_id: "biz_kilyimport",
    title: "MD Distributor License (State of Maryland)",
    category: "Alcohol License",
    status: "Not Started",
    priority: "Medium",
    due_date: d(92),
    renewal_date: d(92 + 365),
    frequency: "Annual",
    assigned_owner: "Marcus Wright",
    agency: "MDBCA",
    jurisdiction: "Maryland",
    requires_document: true,
    document_url: "",
    document_status: "missing",
    reminder_days_before: 45,
    last_completed_date: "2025-08-30",
    notes:
      "Maryland distributor license for warehouse operations. Renewal due before August 30.",
    completion_notes: "",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-40),
  },
  {
    id: "ci_ki_12",
    business_id: "biz_kilyimport",
    title: "Workers' Compensation Insurance",
    category: "Insurance",
    status: "Overdue",
    priority: "Critical",
    due_date: d(-31),
    renewal_date: d(-31 + 365),
    frequency: "Annual",
    assigned_owner: "Marcus Wright",
    agency: "Insurance Broker",
    jurisdiction: "DC / MD",
    requires_document: true,
    document_url: "",
    document_status: "expired",
    reminder_days_before: 30,
    last_completed_date: "2025-04-30",
    notes:
      "Workers' comp lapsed. Broker contacted. Policy must be reinstated ASAP. Fine risk is high.",
    completion_notes: "",
    created_at: "2025-02-15T10:00:00Z",
    updated_at: d(-2),
  },

  // ── Capitol Hill Food Truck ─────────────────────────────────────────────
  {
    id: "ci_ft_01",
    business_id: "biz_foodtruck",
    title: "Mobile Food Unit Permit — Annual",
    category: "Health Permit",
    status: "Due Soon",
    priority: "Critical",
    due_date: d(4),
    renewal_date: d(4 + 365),
    frequency: "Annual",
    assigned_owner: "Priya Patel",
    agency: "DC DOH",
    jurisdiction: "DC",
    requires_document: true,
    document_url: "",
    document_status: "missing",
    reminder_days_before: 30,
    last_completed_date: "2025-06-03",
    notes:
      "Mobile Food Facility Permit. Must be renewed by June 3. Inspection required before issuance.",
    completion_notes: "",
    created_at: "2025-04-01T10:00:00Z",
    updated_at: d(-1),
  },
  {
    id: "ci_ft_02",
    business_id: "biz_foodtruck",
    title: "Commissary Agreement — Union Kitchen",
    category: "Lease / Real Estate",
    status: "Completed",
    priority: "Medium",
    due_date: d(-45),
    renewal_date: d(-45 + 365),
    frequency: "Annual",
    assigned_owner: "Priya Patel",
    agency: "Union Kitchen",
    jurisdiction: "DC",
    requires_document: true,
    document_url: "https://docs.capitolhillft.com/commissary",
    document_status: "uploaded",
    reminder_days_before: 30,
    last_completed_date: "2026-04-15",
    notes: "Annual commissary agreement renewed and on file.",
    completion_notes:
      "Signed 12-month agreement. Rate locked at prior year pricing.",
    created_at: "2025-04-01T10:00:00Z",
    updated_at: "2026-04-15T10:00:00Z",
  },
  {
    id: "ci_ft_03",
    business_id: "biz_foodtruck",
    title: "Health Department Inspection — Scheduled",
    category: "Health Permit",
    status: "Overdue",
    priority: "High",
    due_date: d(-20),
    renewal_date: null,
    frequency: "Annual",
    assigned_owner: "Priya Patel",
    agency: "DC DOH",
    jurisdiction: "DC",
    requires_document: false,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 21,
    last_completed_date: "2025-05-10",
    notes:
      "Annual DOH inspection for mobile food unit. Was rescheduled and missed. Must call to reschedule.",
    completion_notes: "",
    created_at: "2025-04-01T10:00:00Z",
    updated_at: d(-3),
  },
  {
    id: "ci_ft_04",
    business_id: "biz_foodtruck",
    title: "Fire Suppression System Inspection",
    category: "Fire / Safety",
    status: "Not Started",
    priority: "High",
    due_date: d(26),
    renewal_date: d(26 + 365),
    frequency: "Annual",
    assigned_owner: "Priya Patel",
    agency: "DC Fire Marshal",
    jurisdiction: "DC",
    requires_document: true,
    document_url: "",
    document_status: "missing",
    reminder_days_before: 30,
    last_completed_date: "2025-06-25",
    notes:
      "Ansul system inspection required annually. Must use certified inspector.",
    completion_notes: "",
    created_at: "2025-04-01T10:00:00Z",
    updated_at: d(-15),
  },
  {
    id: "ci_ft_05",
    business_id: "biz_foodtruck",
    title: "Vehicle Registration Renewal",
    category: "Vehicle / Fleet",
    status: "Not Started",
    priority: "Medium",
    due_date: d(63),
    renewal_date: d(63 + 365),
    frequency: "Annual",
    assigned_owner: "Priya Patel",
    agency: "DC DMV",
    jurisdiction: "DC",
    requires_document: true,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 30,
    last_completed_date: "2025-08-01",
    notes: "Commercial vehicle registration for food truck. Requires DC safety inspection.",
    completion_notes: "",
    created_at: "2025-04-01T10:00:00Z",
    updated_at: d(-30),
  },
  {
    id: "ci_ft_06",
    business_id: "biz_foodtruck",
    title: "Food Handler Cards — 3 Staff Renewals",
    category: "Food Handler / Safety",
    status: "In Progress",
    priority: "Medium",
    due_date: d(16),
    renewal_date: d(16 + 365),
    frequency: "Annual",
    assigned_owner: "Priya Patel",
    agency: "DC DOH",
    jurisdiction: "DC",
    requires_document: false,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 21,
    last_completed_date: "2025-06-15",
    notes:
      "3 staff members need to renew DC Food Handler certification. 1 already renewed, 2 pending.",
    completion_notes: "",
    created_at: "2025-04-01T10:00:00Z",
    updated_at: d(-5),
  },
  {
    id: "ci_ft_07",
    business_id: "biz_foodtruck",
    title: "City Vending Permit (Public Space)",
    category: "Business License",
    status: "Overdue",
    priority: "Critical",
    due_date: d(-31),
    renewal_date: d(-31 + 365),
    frequency: "Annual",
    assigned_owner: "Priya Patel",
    agency: "DC DCRA / DPW",
    jurisdiction: "DC",
    requires_document: true,
    document_url: "",
    document_status: "expired",
    reminder_days_before: 30,
    last_completed_date: "2025-04-30",
    notes:
      "Public space vending permit required for all Capitol Hill operating locations. Must renew with DPW.",
    completion_notes: "",
    created_at: "2025-04-01T10:00:00Z",
    updated_at: d(-2),
  },
  {
    id: "ci_ft_08",
    business_id: "biz_foodtruck",
    title: "General Liability Insurance Certificate",
    category: "Insurance",
    status: "Overdue",
    priority: "Critical",
    due_date: d(-15),
    renewal_date: d(-15 + 365),
    frequency: "Annual",
    assigned_owner: "Priya Patel",
    agency: "Insurance Broker",
    jurisdiction: "DC",
    requires_document: true,
    document_url: "",
    document_status: "expired",
    reminder_days_before: 30,
    last_completed_date: "2025-05-15",
    notes:
      "GL insurance expired. Renewal quote submitted to broker. Certificate required for vending permit.",
    completion_notes: "",
    created_at: "2025-04-01T10:00:00Z",
    updated_at: d(-3),
  },
  {
    id: "ci_ft_09",
    business_id: "biz_foodtruck",
    title: "Workers' Compensation Insurance",
    category: "Insurance",
    status: "Not Started",
    priority: "High",
    due_date: d(93),
    renewal_date: d(93 + 365),
    frequency: "Annual",
    assigned_owner: "Priya Patel",
    agency: "Insurance Broker",
    jurisdiction: "DC",
    requires_document: true,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 30,
    last_completed_date: "2025-09-01",
    notes: "Workers comp renewal. Currently 2 employees. Check if third hire changes tier.",
    completion_notes: "",
    created_at: "2025-04-01T10:00:00Z",
    updated_at: d(-45),
  },
  {
    id: "ci_ft_10",
    business_id: "biz_foodtruck",
    title: "Q2 Sales Tax Filing (DC OTR)",
    category: "Tax / Excise",
    status: "Not Started",
    priority: "Medium",
    due_date: d(31),
    renewal_date: null,
    frequency: "Quarterly",
    assigned_owner: "Priya Patel",
    agency: "DC OTR",
    jurisdiction: "DC",
    requires_document: false,
    document_url: "",
    document_status: "not_required",
    reminder_days_before: 14,
    last_completed_date: "2026-04-30",
    notes: "Quarterly sales tax return to DC OTR. Due July 31.",
    completion_notes: "",
    created_at: "2025-04-01T10:00:00Z",
    updated_at: d(-7),
  },
];

// ─── ACTIVITY LOGS ─────────────────────────────────────────────────────────

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: "log_1",
    business_id: "biz_lightsleeper",
    compliance_item_id: "ci_ls_09",
    user_id: "user_1",
    action: "Marked complete",
    notes: "Updated all 7 required posters.",
    created_at: "2026-03-15T14:00:00Z",
  },
  {
    id: "log_2",
    business_id: "biz_kilyimport",
    compliance_item_id: "ci_ki_10",
    user_id: "user_1",
    action: "Marked complete",
    notes: "47 SKUs documented.",
    created_at: "2026-04-01T11:00:00Z",
  },
  {
    id: "log_3",
    business_id: "biz_foodtruck",
    compliance_item_id: "ci_ft_02",
    user_id: "user_1",
    action: "Marked complete",
    notes: "Signed 12-month agreement.",
    created_at: "2026-04-15T09:00:00Z",
  },
  {
    id: "log_4",
    business_id: "biz_kilyimport",
    compliance_item_id: "ci_ki_12",
    user_id: "user_concierge",
    action: "Reminder sent",
    notes: "Sent urgent email to Marcus about expired workers comp.",
    created_at: `${T}T08:00:00Z`,
  },
  {
    id: "log_5",
    business_id: "biz_foodtruck",
    compliance_item_id: "ci_ft_01",
    user_id: "user_concierge",
    action: "Document requested",
    notes: "Requested mobile food unit permit docs from Priya.",
    created_at: `${T}T09:30:00Z`,
  },
];

// ─── TEMPLATES ─────────────────────────────────────────────────────────────

export const MOCK_TEMPLATES: Template[] = [
  {
    id: "tmpl_restaurant",
    name: "Restaurant",
    business_type: "Restaurant",
    description:
      "Core compliance checklist for a full-service restaurant. Covers licenses, health, insurance, taxes, and postings.",
    items: [
      {
        id: "ti_r_01",
        template_id: "tmpl_restaurant",
        title: "City Business License Renewal",
        category: "Business License",
        priority: "High",
        frequency: "Annual",
        agency: "City / County Clerk",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 60,
        notes: "Local business license. Required in most jurisdictions.",
      },
      {
        id: "ti_r_02",
        template_id: "tmpl_restaurant",
        title: "State Business License Renewal",
        category: "Business License",
        priority: "High",
        frequency: "Annual",
        agency: "State Secretary of State",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 60,
        notes: "State-level business license or registration.",
      },
      {
        id: "ti_r_03",
        template_id: "tmpl_restaurant",
        title: "Health Department Food Service Permit",
        category: "Health Permit",
        priority: "Critical",
        frequency: "Annual",
        agency: "County / City Health Dept",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 45,
        notes: "Annual food establishment permit. Inspection required.",
      },
      {
        id: "ti_r_04",
        template_id: "tmpl_restaurant",
        title: "Food Handler Cards — Staff Renewal",
        category: "Food Handler / Safety",
        priority: "Medium",
        frequency: "Annual",
        agency: "Health Dept",
        jurisdiction: "State / Local",
        requires_document: false,
        default_reminder_days_before: 30,
        notes: "All food handlers must hold valid certification.",
      },
      {
        id: "ti_r_05",
        template_id: "tmpl_restaurant",
        title: "Workers' Compensation Insurance",
        category: "Insurance",
        priority: "Critical",
        frequency: "Annual",
        agency: "Insurance Provider",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Required if any employees. Verify coverage levels.",
      },
      {
        id: "ti_r_06",
        template_id: "tmpl_restaurant",
        title: "General Liability Insurance Certificate",
        category: "Insurance",
        priority: "High",
        frequency: "Annual",
        agency: "Insurance Provider",
        jurisdiction: "Local / State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "$1M minimum recommended.",
      },
      {
        id: "ti_r_07",
        template_id: "tmpl_restaurant",
        title: "Annual Fire Inspection",
        category: "Fire / Safety",
        priority: "High",
        frequency: "Annual",
        agency: "Local Fire Marshal",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Certificate must be posted. Schedule in advance.",
      },
      {
        id: "ti_r_08",
        template_id: "tmpl_restaurant",
        title: "Required Labor Law Postings — Annual Update",
        category: "Required Posting",
        priority: "Medium",
        frequency: "Annual",
        agency: "DOL / State Labor Dept",
        jurisdiction: "Federal / State",
        requires_document: false,
        default_reminder_days_before: 14,
        notes: "Federal and state labor law posters must be current and posted.",
      },
      {
        id: "ti_r_09",
        template_id: "tmpl_restaurant",
        title: "Quarterly Payroll Tax Filing",
        category: "Tax / Excise",
        priority: "High",
        frequency: "Quarterly",
        agency: "IRS / State Revenue",
        jurisdiction: "Federal / State",
        requires_document: false,
        default_reminder_days_before: 14,
        notes: "IRS 941 and state payroll tax. Due ~1 month after quarter end.",
      },
      {
        id: "ti_r_10",
        template_id: "tmpl_restaurant",
        title: "Annual Corporate / LLC Report",
        category: "Corporate Filing",
        priority: "Medium",
        frequency: "Annual",
        agency: "State Secretary of State",
        jurisdiction: "State",
        requires_document: false,
        default_reminder_days_before: 45,
        notes: "Annual or biennial report to keep entity in good standing.",
      },
    ],
  },
  {
    id: "tmpl_winebar",
    name: "Wine Bar",
    business_type: "Wine Bar",
    description:
      "Compliance checklist for a wine bar with limited food service, retail wine sales, and live entertainment.",
    items: [
      {
        id: "ti_wb_01",
        template_id: "tmpl_winebar",
        title: "City Business License Renewal",
        category: "Business License",
        priority: "High",
        frequency: "Annual",
        agency: "City / County Clerk",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 60,
        notes: "Local business license.",
      },
      {
        id: "ti_wb_02",
        template_id: "tmpl_winebar",
        title: "State Liquor License Renewal",
        category: "Alcohol License",
        priority: "Critical",
        frequency: "Annual",
        agency: "State Liquor Control Board",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 90,
        notes: "On-premise liquor license. Most critical annual item.",
      },
      {
        id: "ti_wb_03",
        template_id: "tmpl_winebar",
        title: "Health Permit",
        category: "Health Permit",
        priority: "High",
        frequency: "Annual",
        agency: "County / City Health Dept",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 45,
        notes: "Food establishment permit even for limited food menus.",
      },
      {
        id: "ti_wb_04",
        template_id: "tmpl_winebar",
        title: "Food Handler Cards",
        category: "Food Handler / Safety",
        priority: "Medium",
        frequency: "Annual",
        agency: "Health Dept",
        jurisdiction: "Local",
        requires_document: false,
        default_reminder_days_before: 30,
        notes: "",
      },
      {
        id: "ti_wb_05",
        template_id: "tmpl_winebar",
        title: "Liquor Liability Insurance",
        category: "Insurance",
        priority: "Critical",
        frequency: "Annual",
        agency: "Insurance Provider",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Dram shop / liquor liability required by liquor board.",
      },
      {
        id: "ti_wb_06",
        template_id: "tmpl_winebar",
        title: "General Liability Insurance",
        category: "Insurance",
        priority: "High",
        frequency: "Annual",
        agency: "Insurance Provider",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "",
      },
      {
        id: "ti_wb_07",
        template_id: "tmpl_winebar",
        title: "Annual Fire Inspection",
        category: "Fire / Safety",
        priority: "High",
        frequency: "Annual",
        agency: "Local Fire Marshal",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "",
      },
      {
        id: "ti_wb_08",
        template_id: "tmpl_winebar",
        title: "Music Licensing Reminder (ASCAP/BMI)",
        category: "Other",
        priority: "Low",
        frequency: "Annual",
        agency: "ASCAP / BMI",
        jurisdiction: "Federal",
        requires_document: false,
        default_reminder_days_before: 30,
        notes: "Blanket license for live and background music.",
      },
      {
        id: "ti_wb_09",
        template_id: "tmpl_winebar",
        title: "Required Employee Postings",
        category: "Required Posting",
        priority: "Medium",
        frequency: "Annual",
        agency: "DOL / State",
        jurisdiction: "Federal / State",
        requires_document: false,
        default_reminder_days_before: 14,
        notes: "",
      },
      {
        id: "ti_wb_10",
        template_id: "tmpl_winebar",
        title: "Annual Corporate / LLC Report",
        category: "Corporate Filing",
        priority: "Medium",
        frequency: "Annual",
        agency: "State Secretary of State",
        jurisdiction: "State",
        requires_document: false,
        default_reminder_days_before: 45,
        notes: "",
      },
    ],
  },
  {
    id: "tmpl_wineimporter",
    name: "Wine Importer",
    business_type: "Wine Importer",
    description:
      "Federal and state compliance for licensed wine importers. Covers TTB, FDA, COLA, excise tax, and state licensing.",
    items: [
      {
        id: "ti_wi_01",
        template_id: "tmpl_wineimporter",
        title: "TTB Basic Importer Permit — Annual Review",
        category: "TTB / Alcohol Federal",
        priority: "Critical",
        frequency: "Annual",
        agency: "TTB",
        jurisdiction: "Federal",
        requires_document: true,
        default_reminder_days_before: 60,
        notes: "TTB Form 5100.24. Required to import wine.",
      },
      {
        id: "ti_wi_02",
        template_id: "tmpl_wineimporter",
        title: "TTB COLA Certificate Tracker",
        category: "TTB / Alcohol Federal",
        priority: "Medium",
        frequency: "Custom",
        agency: "TTB",
        jurisdiction: "Federal",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Track all active COLA certificates for labeling compliance.",
      },
      {
        id: "ti_wi_03",
        template_id: "tmpl_wineimporter",
        title: "FDA Facility Registration Renewal",
        category: "FDA / Federal",
        priority: "High",
        frequency: "Biennial",
        agency: "FDA",
        jurisdiction: "Federal",
        requires_document: false,
        default_reminder_days_before: 30,
        notes: "Biennial renewal for food importers. Required for FDA-regulated products.",
      },
      {
        id: "ti_wi_04",
        template_id: "tmpl_wineimporter",
        title: "State Importer License Renewal",
        category: "Alcohol License",
        priority: "High",
        frequency: "Annual",
        agency: "State Liquor Board",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 60,
        notes: "State-level importer license. Requirements vary by state.",
      },
      {
        id: "ti_wi_05",
        template_id: "tmpl_wineimporter",
        title: "Federal Excise Tax Return (Quarterly)",
        category: "Tax / Excise",
        priority: "Critical",
        frequency: "Quarterly",
        agency: "TTB",
        jurisdiction: "Federal",
        requires_document: false,
        default_reminder_days_before: 14,
        notes: "TTB FET for wine. Due 14th of month following quarter end.",
      },
      {
        id: "ti_wi_06",
        template_id: "tmpl_wineimporter",
        title: "General Liability Insurance",
        category: "Insurance",
        priority: "Critical",
        frequency: "Annual",
        agency: "Insurance Provider",
        jurisdiction: "Federal / State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Includes product liability rider.",
      },
      {
        id: "ti_wi_07",
        template_id: "tmpl_wineimporter",
        title: "Import Document Archive — Annual Review",
        category: "Vendor Documents",
        priority: "Medium",
        frequency: "Annual",
        agency: "Internal",
        jurisdiction: "Federal",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Annual review of customs clearance, shipper docs, and manifests.",
      },
      {
        id: "ti_wi_08",
        template_id: "tmpl_wineimporter",
        title: "Annual Corporate / LLC Report",
        category: "Corporate Filing",
        priority: "Medium",
        frequency: "Annual",
        agency: "State Secretary of State",
        jurisdiction: "State",
        requires_document: false,
        default_reminder_days_before: 45,
        notes: "",
      },
    ],
  },
  {
    id: "tmpl_foodtruck",
    name: "Food Truck",
    business_type: "Food Truck",
    description:
      "Mobile food vendor compliance covering permits, vehicle, commissary, insurance, and health inspections.",
    items: [
      {
        id: "ti_ft_01",
        template_id: "tmpl_foodtruck",
        title: "Mobile Food Unit Permit",
        category: "Health Permit",
        priority: "Critical",
        frequency: "Annual",
        agency: "County / City Health Dept",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Required to legally operate as a mobile food unit.",
      },
      {
        id: "ti_ft_02",
        template_id: "tmpl_foodtruck",
        title: "Commissary Agreement",
        category: "Lease / Real Estate",
        priority: "Medium",
        frequency: "Annual",
        agency: "Commissary Operator",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Required by health dept. Signed agreement on file.",
      },
      {
        id: "ti_ft_03",
        template_id: "tmpl_foodtruck",
        title: "Health Department Inspection",
        category: "Health Permit",
        priority: "High",
        frequency: "Annual",
        agency: "County / City Health Dept",
        jurisdiction: "Local",
        requires_document: false,
        default_reminder_days_before: 21,
        notes: "Annual inspection. Schedule 3–4 weeks in advance.",
      },
      {
        id: "ti_ft_04",
        template_id: "tmpl_foodtruck",
        title: "Fire Suppression System Inspection",
        category: "Fire / Safety",
        priority: "High",
        frequency: "Annual",
        agency: "Local Fire Marshal",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Ansul/suppression system. Must use certified inspector.",
      },
      {
        id: "ti_ft_05",
        template_id: "tmpl_foodtruck",
        title: "Vehicle Registration Renewal",
        category: "Vehicle / Fleet",
        priority: "Medium",
        frequency: "Annual",
        agency: "DMV",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Commercial vehicle registration. Safety inspection may be required.",
      },
      {
        id: "ti_ft_06",
        template_id: "tmpl_foodtruck",
        title: "General Liability Insurance",
        category: "Insurance",
        priority: "Critical",
        frequency: "Annual",
        agency: "Insurance Provider",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Required for vending permit applications.",
      },
      {
        id: "ti_ft_07",
        template_id: "tmpl_foodtruck",
        title: "Food Handler Cards — Staff",
        category: "Food Handler / Safety",
        priority: "Medium",
        frequency: "Annual",
        agency: "Health Dept",
        jurisdiction: "Local",
        requires_document: false,
        default_reminder_days_before: 21,
        notes: "",
      },
      {
        id: "ti_ft_08",
        template_id: "tmpl_foodtruck",
        title: "City Vending / Public Space Permit",
        category: "Business License",
        priority: "Critical",
        frequency: "Annual",
        agency: "City / DPW",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Required for operating on public streets or in permitted zones.",
      },
    ],
  },
  {
    id: "tmpl_salon",
    name: "Salon",
    business_type: "Salon",
    description:
      "Compliance checklist for hair salons, nail salons, and similar cosmetology businesses.",
    items: [
      {
        id: "ti_sl_01",
        template_id: "tmpl_salon",
        title: "State Cosmetology / Salon License",
        category: "Business License",
        priority: "Critical",
        frequency: "Annual",
        agency: "State Board of Cosmetology",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 60,
        notes: "Salon license to operate. Required before opening.",
      },
      {
        id: "ti_sl_02",
        template_id: "tmpl_salon",
        title: "Individual Practitioner Licenses",
        category: "Business License",
        priority: "High",
        frequency: "Biennial",
        agency: "State Board of Cosmetology",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 60,
        notes: "Each stylist/cosmetologist must maintain active license.",
      },
      {
        id: "ti_sl_03",
        template_id: "tmpl_salon",
        title: "City Business License",
        category: "Business License",
        priority: "High",
        frequency: "Annual",
        agency: "City / County Clerk",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 60,
        notes: "",
      },
      {
        id: "ti_sl_04",
        template_id: "tmpl_salon",
        title: "Professional Liability Insurance",
        category: "Insurance",
        priority: "High",
        frequency: "Annual",
        agency: "Insurance Provider",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Protects against claims related to services rendered.",
      },
      {
        id: "ti_sl_05",
        template_id: "tmpl_salon",
        title: "Required Labor Postings",
        category: "Required Posting",
        priority: "Medium",
        frequency: "Annual",
        agency: "DOL / State Labor",
        jurisdiction: "Federal / State",
        requires_document: false,
        default_reminder_days_before: 14,
        notes: "",
      },
      {
        id: "ti_sl_06",
        template_id: "tmpl_salon",
        title: "Quarterly Sales Tax Filing",
        category: "Tax / Excise",
        priority: "High",
        frequency: "Quarterly",
        agency: "State Revenue Dept",
        jurisdiction: "State",
        requires_document: false,
        default_reminder_days_before: 14,
        notes: "Sales tax on products and some services.",
      },
      {
        id: "ti_sl_07",
        template_id: "tmpl_salon",
        title: "Annual Corporate / LLC Report",
        category: "Corporate Filing",
        priority: "Medium",
        frequency: "Annual",
        agency: "State Secretary of State",
        jurisdiction: "State",
        requires_document: false,
        default_reminder_days_before: 45,
        notes: "",
      },
    ],
  },
  {
    id: "tmpl_contractor",
    name: "Contractor",
    business_type: "Contractor",
    description:
      "License, bond, insurance, and filing requirements for general and specialty contractors.",
    items: [
      {
        id: "ti_co_01",
        template_id: "tmpl_contractor",
        title: "Contractor License Renewal",
        category: "Contractor License",
        priority: "Critical",
        frequency: "Annual",
        agency: "State Contractors Board",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 60,
        notes: "State contractor license. Required to legally operate.",
      },
      {
        id: "ti_co_02",
        template_id: "tmpl_contractor",
        title: "Contractor Bond Renewal",
        category: "Insurance",
        priority: "Critical",
        frequency: "Annual",
        agency: "Bonding Company",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Surety bond required by contractor license.",
      },
      {
        id: "ti_co_03",
        template_id: "tmpl_contractor",
        title: "General Liability Insurance Certificate",
        category: "Insurance",
        priority: "Critical",
        frequency: "Annual",
        agency: "Insurance Provider",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "$1M per occurrence minimum.",
      },
      {
        id: "ti_co_04",
        template_id: "tmpl_contractor",
        title: "Workers' Compensation Insurance",
        category: "Insurance",
        priority: "Critical",
        frequency: "Annual",
        agency: "Insurance Provider",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Required for any employees. Verify payroll classification.",
      },
      {
        id: "ti_co_05",
        template_id: "tmpl_contractor",
        title: "Vehicle Registration & Insurance",
        category: "Vehicle / Fleet",
        priority: "Medium",
        frequency: "Annual",
        agency: "DMV / Insurance",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "Commercial vehicle registration and auto insurance.",
      },
      {
        id: "ti_co_06",
        template_id: "tmpl_contractor",
        title: "City Business License",
        category: "Business License",
        priority: "High",
        frequency: "Annual",
        agency: "City / County Clerk",
        jurisdiction: "Local",
        requires_document: true,
        default_reminder_days_before: 60,
        notes: "",
      },
      {
        id: "ti_co_07",
        template_id: "tmpl_contractor",
        title: "Annual Corporate / LLC Report",
        category: "Corporate Filing",
        priority: "Medium",
        frequency: "Annual",
        agency: "State Secretary of State",
        jurisdiction: "State",
        requires_document: false,
        default_reminder_days_before: 45,
        notes: "",
      },
    ],
  },
  {
    id: "tmpl_winedistributor",
    name: "Wine Distributor",
    business_type: "Wine Distributor",
    description:
      "State distribution license, excise tax, supplier agreements, and operational compliance for wine distributors.",
    items: [
      {
        id: "ti_wd_01",
        template_id: "tmpl_winedistributor",
        title: "State Distributor License Renewal",
        category: "Alcohol License",
        priority: "Critical",
        frequency: "Annual",
        agency: "State Liquor Control Board",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 90,
        notes: "Primary state distributor license.",
      },
      {
        id: "ti_wd_02",
        template_id: "tmpl_winedistributor",
        title: "Liquor Board Reporting Deadline",
        category: "State LCB / Liquor Board",
        priority: "High",
        frequency: "Monthly",
        agency: "State Liquor Control Board",
        jurisdiction: "State",
        requires_document: false,
        default_reminder_days_before: 7,
        notes: "Monthly sales and inventory reporting.",
      },
      {
        id: "ti_wd_03",
        template_id: "tmpl_winedistributor",
        title: "State Excise Tax Filing",
        category: "Tax / Excise",
        priority: "Critical",
        frequency: "Monthly",
        agency: "State Revenue Dept",
        jurisdiction: "State",
        requires_document: false,
        default_reminder_days_before: 7,
        notes: "Monthly excise tax on wine distributed.",
      },
      {
        id: "ti_wd_04",
        template_id: "tmpl_winedistributor",
        title: "Insurance Certificates",
        category: "Insurance",
        priority: "High",
        frequency: "Annual",
        agency: "Insurance Provider",
        jurisdiction: "State",
        requires_document: true,
        default_reminder_days_before: 30,
        notes: "GL, vehicle, warehouse, and product liability.",
      },
      {
        id: "ti_wd_05",
        template_id: "tmpl_winedistributor",
        title: "Annual Corporate / LLC Report",
        category: "Corporate Filing",
        priority: "Medium",
        frequency: "Annual",
        agency: "State Secretary of State",
        jurisdiction: "State",
        requires_document: false,
        default_reminder_days_before: 45,
        notes: "",
      },
    ],
  },
];
